### ISSUE TITLE
Сенсоры мобильных устройств создались, но на карте не отражаются

### ISSUE THREAD

**Issue by sergey-1976** [mavrikkk/ha_routes#5]
Добрый день. 

Версия Home Assistant 2021.1.5

Сенсоры мобильных устройств создались, но на карте не отражаются.

Объекты:
SM-G930F device_tracker.sm_g930f Mobile App
virtual_device_tracker_sm_g930f sensor.virtual_device_tracker_sm_g930f Сенсор

В конфиге:
route:
  days: 3
  mindst: 1
  time_zone: +03:00
  token: "мой токен"
  devices:
    - device_tracker.sm_g930f
    - sensor.virtual_device_tracker_sm_g930f

В журнале:
virtual_device_tracker_sm_g930f изменяет состояние на "2021-02-08 16:20:41"
virtual_device_tracker_sm_g930f изменяет состояние на "2021-02-08 16:14:41"
virtual_device_tracker_sm_g930f изменяет состояние на "2021-02-08 15:59:41"

**Comment by sergey-1976** [comment]
проблема с base_url
работает только "снаружи"

**Comment by PandaGirll** [comment]
Добрый день!

Та же проблема.
MapCard данные видит, а routes - нет.

routes настроен:

```
route:
  days: 10
  mindst: 1
  time_zone: '+03:00'
  token: !secret long_token
  devices:
    - sensor.nika
    - sensor.alex
```
сенсоры сделала, в них данные есть:

 ```
 - platform: template
    sensors:
      alex:
        value_template: "{{states.device_tracker.google_maps_****.last_updated}}"
        attribute_templates:
          latitude: >
            {{ state_attr('device_tracker.google_maps_****','latitude') }}
          longitude: >
            {{ state_attr('device_tracker.google_maps_****','longitude') }}`
```

base_url - есть. Кстати, HA ругается, что этот параметр depricated.
```
  external_url: !secret external_url
  internal_url: !secret internal_url 
http:
  ip_ban_enabled: true
  login_attempts_threshold: 5
  base_url: !secret external_url
```
сам url имеет такой вид: https://mysite.dataplicity.io/
В журнале событий данные есть, история есть.
![image](https://user-images.githubusercontent.com/32674686/118361024-3260f600-b592-11eb-947a-ec2e7055b1bf.png)
![image](https://user-images.githubusercontent.com/32674686/118361084-705e1a00-b592-11eb-9dc0-4d2decaac218.png)
![image](https://user-images.githubusercontent.com/32674686/118361118-8f5cac00-b592-11eb-8929-151732074682.png)
![image](https://user-images.githubusercontent.com/32674686/118361448-283ff700-b594-11eb-9e22-9473dd395453.png)
